version: '3.9'

services:
  postgres-db:
    image: 'postgres:15.0-alpine'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: grupo4
      POSTGRES_DB: LosVinos
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - demorepo_net
    healthcheck:
      test: ["CMD", "pg_isready"]
      start_period: 30s

  demorepo-app:
    image: nadinechancay/demorepo-demorepo-app
    build: .
    restart: always
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    # volumes:
    #   - .:/demorepo
    ports:
      - 8000:8000
    depends_on:
      - postgres-db
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=grupo4
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=LosVinos
    networks:
      - demorepo_net
      
volumes:
  postgres_data:

networks:
  demorepo_net:
