version: '3.9'

services:
  postgres-db:
    image: 'postgres:15.0-alpine'
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - demorepo_net
    healthcheck:
      test: ["CMD", "pg_isready"]
      start_period: 30s

  demorepo-app:
    build: .
    restart: always
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/demorepo
    ports:
      - 8000:8000
    depends_on:
      - postgres-db
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres-db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    networks:
      - demorepo_net
      
volumes:
  postgres_data:

networks:
  demorepo_net:
